// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    TabPanel: typeof import('@headlessui/vue')['TabPanel']
    TabPanels: typeof import('@headlessui/vue')['TabPanels']
  }
}
